spring.activemq.broker-url=tcp://192.168.111.6:61616
spring.activemq.user=admin
spring.activemq.password=admin

# Channel-Konfiguration (vorgegebene Fremdsystem-Channels)
channel.topic.newJobs=group6.dispo.jobs.new
channel.queue.requestAssignment=group6.dispo.jobs.requestAssignment
channel.topic.assignments=group6.dispo.jobs.assignments

# Eigene Channels müssen mit group6. beginnen!
# Beispiel: group6.myTopic, group6.myQueue
